export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const POSTS_ROUTE = '/'
export const FAVORITE_ROUTE = '/favorite'
export const FOOD_ROUTE = '/food'